"""Generate docs/metrics-catalog.md from the YAML definitions.

    python scripts/generate_metrics_catalog.py           # write the file
    python scripts/generate_metrics_catalog.py --check   # exit 1 if it is stale (for CI)

The catalog is generated rather than hand-written so it cannot drift from the definitions the
agent actually uses. A hand-maintained catalog that disagrees with the registry is worse than no
catalog: a reviewer would be checking the agent's arithmetic against the wrong formula.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

OUTPUT = ROOT / "docs" / "metrics-catalog.md"

HEADER = """# Approved metrics catalogue

<!-- Generated by scripts/generate_metrics_catalog.py. Do not edit by hand. -->

These are the business metric definitions the agent is allowed to use. It resolves a term in a
question to one of these and reports the version it used, so a conclusion names the definition
behind its numbers.

The agent **may not invent a formula**. A term with no approved definition here comes back as
`NotApproved`, and the agent must either ask which definition is meant or state explicitly that
it is using an ad-hoc one.

For an `aggregate` metric, the registry assembles the statement from the reviewed parts below
and binds every value as a parameter, so no free text from the model reaches SQL. A `custom`
metric carries its own statement, and is held to the same bar by the test that asserts every
rendered metric passes `sql_guard`.

Source: `src/analyst_agent/metrics/definitions/*.yaml` · Registry:
`src/analyst_agent/metrics/registry.py`
"""


def render() -> str:
    from analyst_agent.metrics.registry import get_registry

    registry = get_registry()
    parts = [HEADER, "\n## Summary\n", "| Metric | Title | Unit | Grain | Shape | Owner |", "|---|---|---|---|---|---|"]
    for definition in registry.all():
        parts.append(
            f"| `{definition.name}` | {definition.title} | {definition.unit} | "
            f"{definition.grain} | {definition.shape} | {definition.owner} |"
        )

    parts.append("\n---\n")

    for definition in registry.all():
        parts.append(f"## `{definition.name}` — {definition.title}\n")
        parts.append(f"*Version {definition.version} · {definition.unit} · "
                     f"grain: {definition.grain} · owner: {definition.owner}*\n")
        parts.append(definition.description.strip() + "\n")

        if definition.aliases:
            aliases = ", ".join(f"`{a}`" for a in sorted(definition.aliases))
            parts.append(f"**Also asked as:** {aliases}\n")

        if definition.shape == "aggregate":
            parts.append("**Measure**\n")
            parts.append(f"```sql\n{(definition.measure or '').strip()}\n```\n")
            parts.append("**Read from**\n")
            parts.append(f"```sql\n{(definition.from_sql or '').strip()}\n```\n")
            if definition.where_sql:
                parts.append("**Filter**\n")
                parts.append(f"```sql\n{definition.where_sql.strip()}\n```\n")
            parts.append(f"**Dated by** `{definition.date_column}`\n")

            if definition.dimensions:
                parts.append("**Dimensions**\n")
                parts.append("| Name | Label | Expression | Extra join |")
                parts.append("|---|---|---|---|")
                for name, dimension in definition.dimensions.items():
                    join = f"`{dimension.join}`" if dimension.join else "—"
                    parts.append(
                        f"| `{name}` | {dimension.label} | `{dimension.sql}` | {join} |"
                    )
                parts.append("")
        else:
            parts.append("**Statement** (custom shape — owns its own grouping)\n")
            parts.append(f"```sql\n{(definition.custom_sql or '').strip()}\n```\n")

        parts.append("**Caveats**\n")
        for caveat in definition.caveats:
            parts.append(f"- {' '.join(caveat.split())}")
        parts.append("")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the file is stale")
    args = parser.parse_args()

    generated = render()

    if args.check:
        if not OUTPUT.is_file():
            print(f"[catalog] {OUTPUT.name} does not exist", file=sys.stderr)
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(
                f"[catalog] {OUTPUT.name} is stale. Run "
                "`python scripts/generate_metrics_catalog.py`.",
                file=sys.stderr,
            )
            return 1
        print(f"[catalog] {OUTPUT.name} is up to date")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"[catalog] wrote {OUTPUT.relative_to(ROOT)} ({len(generated.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
